version: '3.8'

service:
  web:
    build:.
    ports:
        -"8000:8000"
      volumes:
        -./src:/app/src
        -./media:/app/media
      enviroment:
        -DJANGO_ENV = development
        -REDIS_URL = redis://localhost:6379/0
        -CELERY_BROKER_URL = redis://localhost:6379/0
      depends_on:
        -redis
      command:python  src/manage.py runserver 0.0.0.0:8000

    redis:
      image:redis:7-alpine
      ports:
        -"6379:6379"

    celery:
      build:.
      command:celery -A config worker -loglevel=info
      enviroment:
        -DJANGO_ENV = development
        -REDIS_URL = redis://localhost:6379/0
        -CELERY_BROKER_URL = redis://localhost:6379/0
      depends_on:
        -redis
      volumes:
        -./src:/app/src 
        -CELERY_BROKER_URL = redis://localhost:6379/0
      depends_on:
        -redis
      volumes:
        -./src:/app/src

